name: git push into another repo to deploy to vercel

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    types: [closed]
    branches: ["main", "dev"]
  workflow_dispatch:  # 수동 트리거 추가

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTO_ACTIONS }}
        with:
          source-directory: '.'  # 전체 레포지토리를 전송
          destination-github-username: ${{ secrets.USER_NAME }}
          destination-repository-name: ${{ secrets.REPO_NAME }}
          user-email: ${{ secrets.EMAIL }}
          commit-message: "Sync from source repo: ${{ github.event.commits[0].message }}"
          target-branch: main
