name: Sync Organization Repo to Personal Repo

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    types: [closed]
    branches: ["main", "dev"]
  workflow_dispatch:  # 수동 트리거 추가

permissions:
  contents: write  # 푸시 권한 추가

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the organization repository
        uses: actions/checkout@v3
        with:
          ref: main  # 조직 레포지토리의 main 브랜치 체크아웃

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Configure git user
        run: |
          git config --global user.name "${{ secrets.USER_NAME }}"
          git config --global user.email "${{ secrets.EMAIL }}"

      - name: Add remote for personal private repository
        run: |
          git remote add personal git@github.com:${{ secrets.USER_NAME }}/${{ secrets.PERSONAL_REPO_NAME }}.git
          git fetch personal

      - name: Push changes to personal private repository
        run: |
          git push personal main --force-with-lease  # --force-with-lease로 강제 푸시
