name: Sync Fork with Upstream

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    types: [closed]
    branches: ["main", "dev"]
  workflow_dispatch:  # 수동 트리거 추가

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 원본 레포지토리의 내용 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # GitHub 액세스를 위한 설정
      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      # 포크한 레포지토리 리모트 추가
      - name: Add fork remote
        run: git remote add fork https://github.com/PSangEon/lookids-fe.git

      # Personal Access Token을 사용하여 인증 설정
      - name: Set up authentication
        run: |
          git config --global credential.helper store
          echo "https://x-access-token:${{ secrets.AUTO_ACTIONS }}@github.com" > ~/.git-credentials

      # 변경 사항을 포크한 레포지토리에 푸시
      - name: Push changes to fork
        run: |
          git push fork dev
