name: Clone and Push to Another Repo

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    types: [closed]
    branches: ["main", "dev"]
  workflow_dispatch:  # 수동 트리거 추가

jobs:
  clone_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the source repository
        uses: actions/checkout@v2
      
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTO_ACTIONS }}
        with:
          source-directory: '.' # 현재 저장소의 모든 내용을 복제
          destination-github-username: ${{ secrets.USER_NAME }}
          destination-repository-name: ${{ secrets.REPO_NAME }}
          user-email: ${{ secrets.EMAIL }}
          commit-message: 'Clone and deploy'
          target-branch: main

      - name: Confirm destination cloned directory
        run: echo $DESTINATION_CLONED_DIRECTORY
