name: git push into another repo to deploy to vercel

on:
  push:
    branches: ["main"]
  pull_request:
    types: [closed]
    branches: ["main", "dev"]
  workflow_dispatch:  # 수동 트리거 추가
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Git
        uses: actions/setup-git@v2

      - name: Configure git user
        run: |
          git config --global user.name ${{ secrets.USER_NAME }}
          git config --global user.email ${{ secrets.EMAIL }}

      - name: Add remote fork
        run: |
          git remote add fork https://github.com/${{ secrets.USER_NAME }}/${{ secrets.REPO_NAME }}.git
          git fetch fork

      - name: Push changes to fork
        run: |
          git push fork main --force  # main 브랜치에 강제로 푸시
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
