name: Sync Fork with Upstream

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    types: [closed]
    branches: ["main", "dev"]
  workflow_dispatch:  # 수동 트리거 추가

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 원본 레포지토리의 내용 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add remote-url
        run: |
          git remote add forked-repo https://PSangEon:${{ secrets.AUTO_ACTIONS }}@github.com/PSangEon/lookids-fe.git
          git config user.name PSangEon
          git config user.email qkr99102@naver.com
      
      - name: Push changes to forked-repo 
        run: |
          git push -f forked-repo main
      
      - name: Clean up
        run: |
          git remote remove forked-repo
          
      # # GitHub 액세스를 위한 설정
      # - name: Set up Git
      #   run: |
      #     git config user.name "PSangEon"
      #     git config user.email "qkr99102@naver.com"

      # # Personal Access Token을 사용하여 인증 설정
      # - name: Set up authentication
      #   run: |
      #     echo "https://x-access-token:${{ secrets.AUTO_ACTIONS }}@github.com" > ~/.git-credentials
      #     git config --global credential.helper store

      # # 포크한 레포지토리 리모트 추가
      # - name: Add fork remote
      #   run: git remote add fork https://github.com/PSangEon/lookids-fe.git

      # # 변경 사항을 포크한 레포지토리에 푸시
      # - name: Push changes to fork
      #   run: |
      #     git push fork dev

          
